![](Bellman.png)

In [1]:
import numpy as np
import random

In [2]:
dimensiones = (5, 5)
estado_inicial = (0, 0)
estado_objetivo = (4, 4)
obstaculos = [(1, 1), (1, 3), (2, 3), (3, 0)]
acciones = [(-1, 0), (1, 0), (0, -1), (0, 1)]

In [3]:
num_estados = dimensiones[0] * dimensiones[1]
num_estados

25

In [4]:
num_acciones = len(acciones)
num_acciones

4

In [5]:
Q = np.zeros((num_estados, num_acciones))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
def estado_a_indice(estado):
    return estado[0] * dimensiones[1] + estado[1]

In [7]:
ejemplo = estado_a_indice((1, 0))
ejemplo

5

In [8]:
alpha = 0.1
gamma = 0.99
epsilon = 0.2
episodios = 100

In [9]:
def indice_a_estado(indice):
    """
    Convierte un índice lineal a una representación bidimensional del estado en la cuadrícula.
 
    Argumentos:
    indice -- un entero que representa el índice lineal.
    num_columnas -- número de columnas en la cuadrícula (por defecto 5).
 
    Retorna:
    Una tupla (fila, columna) que representa el estado en la cuadrícula.
    """
    num_columnas=5
    fila = indice // num_columnas
    columna = indice % num_columnas
    return (fila, columna)
 
# Ejemplo de prueba:
# El estado correspondiente al índice 5 en una cuadrícula de dimensiones (5, 5) debería ser (1, 0).
print(indice_a_estado(10))  # Debe imprimir: (1, 0)

(2, 0)


In [11]:
import numpy as np
import random

# Parámetros globales para la función elegir_accion
epsilon = 0.1
num_acciones = 4
Q = np.zeros((25, num_acciones))  # Ejemplo de matriz Q
dimensiones = (5, 5)

def estado_a_indice(estado):
    # Convierte el estado en un índice para la matriz Q
    return estado[0] * dimensiones[1] + estado[1]

def elegir_accion(estado):
    if random.uniform(0, 1) < epsilon:
        return random.choice(range(num_acciones))
    else:
        return np.argmax(Q[estado_a_indice(estado)])
    pass

In [12]:
import numpy as np
# Variables de configuración
acciones = [(0, -1), (1, 0), (0, 1), (-1, 0)]  # Movimientos: izquierda, abajo, derecha, arriba
dimensiones = (5, 5)  # Dimensiones del grid
obstaculos = [(2, 2), (3, 3)]  # Posiciones de obstáculos
estado_objetivo = (4, 4)  # Posición del objetivo

def aplicar_accion(estado, accion_idx):
    """
    Aplica una acción basada en un índice de acción dado y actualiza el estado del agente en el grid.

    Parámetros:
    - estado (tuple): La posición actual del agente en el grid.
    - accion_idx (int): El índice de la acción a aplicar, que está basado en la lista 'acciones'.

    Retorna:
    - tuple: El nuevo estado del agente después de aplicar la acción.
    - int: La recompensa o penalización resultante de la acción.
    - bool: Un booleano que indica si el objetivo ha sido alcanzado.
    """
    accion = acciones[accion_idx]
    nuevo_estado = tuple(np.add(estado, accion) % dimensiones)
 
    if nuevo_estado in obstaculos:
        return estado, -100, False
    elif nuevo_estado == estado_objetivo:
        return nuevo_estado, 100, True
    else:
        return nuevo_estado, -1, False
    pass

In [13]:
for episodio in range(episodios):
    estado = estado_inicial
    terminado = False
    
    while not terminado:
        idx_estado = estado_a_indice(estado)
        accion_idx = elegir_accion(estado)
        nuevo_estado, recompensa, terminado = aplicar_accion(estado, accion_idx)
        idx_nuevo_estado = estado_a_indice(nuevo_estado)
        
        Q[idx_estado, accion_idx] = Q[idx_estado, accion_idx] + alpha * (recompensa + gamma * np.max(Q[idx_nuevo_estado]) - Q[idx_estado, accion_idx])
        
        estado = nuevo_estado

In [14]:
politica = np.zeros(dimensiones, dtype=int)
politica

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
for i in range(dimensiones[0]):
    for j in range(dimensiones[1]):
        estado = (i, j)
        idx_estado = estado_a_indice(estado)
        mejor_accion = np.argmax(Q[idx_estado])
        politica[i, j] = mejor_accion
        
print("Política aprendida (0: arriba, 1: abajo, 2: izquierda, 3: derecha)")
print(politica)

Política aprendida (0: arriba, 1: abajo, 2: izquierda, 3: derecha)
[[3 0 3 3 3]
 [3 2 2 1 1]
 [1 2 0 2 0]
 [0 1 0 0 1]
 [0 0 0 0 0]]
